### ISSUE TITLE
Support for swarm affinity env variable 

### ISSUE THREAD

**Issue by monovaldes** [prologic/autodock-hipache#4]
Thera is a specific swarm attribute: 
affinity:container== 
which breaks the dict command used in line 87 of autodock-hipache
<code>env = dict([e.split("=") for e in info["Config"]["Env"]])</code>
proposed alternative:
<code>env = dict([e.replace("==","=").split("=") for e in info["Config"]["Env"]])</code>
cheers

**Comment by prologic** [comment]
:+1: I'll fix that straight away! THanks!

How are you using autodock? As a minimal PaaS?

**Comment by monovaldes** [comment]
Yep,  for internal webservices such as hgserve and redmine :)  cheers

**Comment by prologic** [comment]
Ahh cool! I use autodock (*and built it!*) to host several production websites as well as quite a few internal web apps and services too :)
